# Generated by Django 2.2.5 on 2019-10-23 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledcourse',
            unique_together={('user', 'course')},
        ),
    ]
