# Generated by Django 2.2.5 on 2019-11-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_submission_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_grade',
            field=models.IntegerField(default=0),
        ),
    ]
