# Generated by Django 2.2.5 on 2019-11-16 14:47

from django.db import migrations, models
import django.db.models.deletion
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=question.models.get_question_media_location),
        ),
        migrations.AlterField(
            model_name='media',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='question.Question'),
        ),
    ]
