# Generated by Django 2.2.5 on 2019-11-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_mcqoption_mcqquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquestion',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='McqOption',
        ),
        migrations.DeleteModel(
            name='McqQuestion',
        ),
    ]
