# Generated by Django 2.2.5 on 2019-11-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20191117_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(default='no description provided by tutor', max_length=500),
        ),
    ]
