# Generated by Django 2.2.5 on 2019-10-25 09:31

import assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20191019_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='solution_pdf',
            field=models.FileField(null=True, upload_to=assignment.models.get_upload_location),
        ),
    ]
